# HOW TO EXPOSE THIS MANIFEST
# ---------------------------
# kubectl port-forward -n ${NAMESPACE} deployment/nginx ${NGINX_PORT}:80
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: ${NAMESPACE}
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: ${REGISTRY}/${NAMESPACE}/nginx:${TAG}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: ${NGINX_PORT}