# HOW TO EXPOSE THIS MANIFEST
# ---------------------------
# kubectl port-forward -n ${NAMESPACE} deployment/jenkins ${JENKINS_PORT}:8080
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: ${NAMESPACE}
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      nodeSelector:
        jenkins: anchor-stateful
      securityContext:
        runAsUser: 0 # Allow access to /var/jenkins_home
      restartPolicy: Always
      containers:
        - name: jenkins
          image: ${REGISTRY}/${NAMESPACE}/jenkins:${TAG}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: ${JENKINS_PORT}
          volumeMounts:
            - name: jenkins-data
              mountPath: /var/jenkins_home
      volumes:
        - name: jenkins-data
          hostPath:
            path: /opt/stateful/jenkins